### ISSUE TITLE
Calling SubmarineView.float from Java

### ISSUE THREAD

**Issue by RobbWatershed** [skydoves/Submarine#3]
For us mortals who still use Java instead of Kotlin, naming a method `float` confuses the compiler _a lot_,as `float` is a keyword referring to the primitive type of the same name.

Any tip other than using reflection to make that work properly ?

**Comment by skydoves** [comment]
Oh.. I almost didn't notice that.
I just changed names to `floats()`, `dips()`, `navigates()`, and `retreats()` and released a new `1.0.5` version.
Thanks for your issue!

**Comment by RobbWatershed** [comment]
Well, that was quick !  Thanks a lot 👍
