### ISSUE TITLE
Request : setDismissWhenTouchOutside

### ISSUE THREAD

**Issue by RobbWatershed** [skydoves/Submarine#4]
Would it be possible to add a feature similar to Balloon's `setDismissWhenTouchOutside` ?

I'm using Submarine as a micro menu that users can unfold and then either select or choose to ignore. The natual gesture for doing that is to touch outside of the menu... just like what you implemented on Balloon 🙃

**Comment by skydoves** [comment]
Ah, the `SubmarinVIew` is actually a View (not a pop-up window), so we can implement it using the `View.OnTouchListener`.

**Comment by RobbWatershed** [comment]
If you are saying I can do that easily on my side, is there any place where I can find inspiration / sample working code ?

**Comment by skydoves** [comment]
Probably this [solution](https://stackoverflow.com/a/39428663) could be helpful.

**Comment by RobbWatershed** [comment]
That's great, thanks ! It's all the more easy as I already use `onTouchEvent` for that fragment.
