### ISSUE TITLE
Feature request : Define a tooltip text for each SubmarineItem

### ISSUE THREAD

**Issue by RobbWatershed** [skydoves/Submarine#5]
My users would like know the meaning of each item by having a tooltip text displayed on long-press (same as `android:tooltipText`)

Would it be possible to define a tooltip text for each item we add ?

**Comment by skydoves** [comment]
Hi, @RobbWatershed 
This looks great feature. I will implement this feature in the next release.
Thanks :)

**Comment by skydoves** [comment]
Included in the `1.0.6-SNAPSHOT`.

**Comment by RobbWatershed** [comment]
Where may I find this snapshot ? I tried updating my gradle import but it failed to resolve...

**Comment by skydoves** [comment]
Oh, I forgot to add a snapshot guideline on the README.

Snapshots of the current development version of Submarine are available, which track the latest versions.

repositories {
   maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

versions: `1.0.6-SNAPSHOT`

**Comment by skydoves** [comment]
Released a new stable version `1.0.6`.
Thanks for your issue :)

**Comment by RobbWatershed** [comment]
Just tested it and it's all fine ! Thanks a lot ❤️
